name: Continuous Integration with Docker

on:
  pull_request:
    branches:
      - main

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Cria o .env com o conteúdo do example
      - name: Create .env file
        run: cp .env.example .env


      # Subir os serviços
      - name: Setup Project
        run: |
          make setup

      # Esperar os serviços
      - name: Wait for services
        run: sleep 10

      # Executar os testes
      - name: Run tests
        run: |
          docker-compose exec app php artisan test

      # Derrubar os serviços
      - name: Tear down Docker
        if: always()
        run: |
          docker-compose down
