name: Continuous Integration with Docker

on:
  pull_request:
    branches:
      - main

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      # Subir os serviços
      - name: Setup Docker
        run: |
          docker-compose up -d --build
          docker exec laravel-layer-app-1 composer install


      # Esperar os serviços
      - name: Wait for services
        run: sleep 10

      # Executar as migrações
      - name: Run migrations
        run: |
          docker exec laravel-layer-app-1 php artisan migrate --no-interaction --force

      # Executar os testes
      - name: Run tests
        run: |
          docker exec laravel-layer-app-1 php artisan test --no-interaction

      # Derrubar os serviços
      - name: Tear down Docker
        if: always()
        run: |
          docker-compose down
